[project]
name = "03-job-server-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.10.6",
    "pypdf2>=3.0.1",
    "requests>=2.32.4",
]
